version: "3.8"
services:
  my-service:
    container_name: my-service
    build:
      context: .
      target: dev
    volumes:
    - .:/app:rw,delegated
    ports:
    - 4000:5000
    - 2345:2345
    
    environment:
      - PORT=5000
      - ENVIRONMENT=productions
      - VERSION=3.8
