version: '3.8'

services:
  furry-adventure:
    image: cosmtrek/air
    working_dir: /furry-adventure
    ports:
      - "4000:5000"
      - "2345:2345"

    volumes:
      - ../:/furry-adventure/
    environment:
      - PORT=5000
      - ENVIRONMENT=productions
      - VERSION=3.8
